# Generated by Django 2.2.6 on 2019-10-24 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicamentinpharmacy',
            old_name='pharmacy',
            new_name='branch',
        ),
    ]
