# Generated by Django 2.2.6 on 2019-10-24 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_auto_20191024_0034'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MedicamentInPharmacy',
            new_name='MedicamentInBranch',
        ),
    ]
